AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template to deploy WordPress on Amazon Linux with LAMP stack'

Parameters:
  InstanceType:
    Description: 'EC2 instance type'
    Type: String
    Default: t2.micro
  SSHLocation:
    Description: 'IP address range for SSH access'
    Type: String
    Default: 0.0.0.0/0
  DBName:
    Description: 'Name of the WordPress database'
    Type: String
    Default: wordpressdb
  DBUser:
    Description: 'Username for the WordPress database'
    Type: String
    Default: localdbuser
  DBPassword:
    Description: 'Password for the WordPress database user from AWS Secrets Manager'
    Type: String
    Default: '{{resolve:secretsmanager:wordpress-lab-db-password:SecretString}}'
    NoEcho: true
  DBRootPassword:
    Description: 'Root password for the MySQL database'
    Type: String
    Default: dummypassword
    NoEcho: true

Resources:
  WordPressInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-085ad6ae776d8f09c
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: lecture_2_setup_tutorial #please-update-with-your-key
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          exec > >(tee /var/log/user-data.log) 2>&1

          dnf update -y
          dnf install -y httpd mariadb105-server mariadb105 php php-mysqlnd wget unzip
          systemctl start httpd
          systemctl enable httpd
          systemctl start mariadb
          systemctl enable mariadb

          mysql_secure_installation <<EOF
          n
          y
          y
          y
          y
          EOF

          mariadb -u root -e "CREATE DATABASE ${DBName};"
          mariadb -u root -e "CREATE USER '${DBUser}'@'localhost' IDENTIFIED BY '${DBPassword}';"
          mariadb -u root -e "GRANT ALL PRIVILEGES ON ${DBName}.* TO '${DBUser}'@'localhost';"
          mariadb -u root -e "FLUSH PRIVILEGES;"

          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cp -r wordpress/* .
          rm -rf wordpress latest.tar.gz
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/${DBName}/" wp-config.php
          sed -i "s/username_here/${DBUser}/" wp-config.php
          sed -i "s/password_here/${DBPassword}/" wp-config.php

          chown -R apache:apache /var/www/html
          chmod -R 755 /var/www/html
          systemctl restart httpd

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  WebsiteURL:
    Description: 'WordPress Website URL'
    Value: !Sub 'http://${WordPressInstance.PublicDnsName}'
